version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - ls -l
      - chmod +x gradlew
      - ./gradlew build
      - mv build/libs/minimal-api-*.jar minimal-api.jar
artifacts:
  files:
    - minimal-api.jar
    - appspec.yml
    - scripts/*
