version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - ls -l
      - chmod +x gradlew
      - ./gradlew build
artifacts:
  files:
    - '*.jar'
  base-directory: 'build/libs'
